#!/bin/bash

LMON=DP2-2
RMON=DP2-3
EMON=eDP1

WIDTH=2560
HEIGHT=1440

RES="${WIDTH}x${HEIGHT}"

single() {
    xrandr --output $EMON --mode 1920x1080 --pos 0x0 --primary \
	   --output $LMON --off \
	   --output $RMON --off
    sleep 1
}

dual() {
    xrandr --output $LMON --mode $RES --primary
    sleep 1

    xrandr --output $EMON --off \
	   --output $LMON --mode $RES --pos 0x0 --primary \
	   --output $RMON --mode $RES --pos ${WIDTH}x0
    sleep 1
}

triple() {
    dual
    xrandr --output $EMON --mode 1920x1080 --pos $(( WIDTH*2 ))x0
    sleep 1
}

if [ $# -eq 1 ]; then
    out=$1
else
    out=$(echo 1 LaptopOnly 2 Dualscreen 3 Dualscreen+Extended | sed 's/ /\n/g' | zenity --list --column "" --column "")
fi

xrandr --addmode $LMON $RES
xrandr --addmode $RMON $RES

case "$out" in
	1) single ;;
	2) dual ;;
	3) triple ;;
esac

# restore wallpaper
nitrogen --restore
